# 1.Lesson: Numpy Array

In [1]:
import numpy as np

## Numpy Array

* Numpy array leri python listlerine benziyor

* Ama onların aksine, farklı veri tiplerinde elemanlar içermez. Tek veri tipinde elemanları olması gerekiyor

## Listlerden Array Oluşturmak

In [2]:
x = np.array([1, 2, 3, 4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array(['a', 'b', 'c'])

In [6]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
## Bütün integer lar stringe dönüştürülecek

z = np.array([1, 2, 3, 'a'])

In [8]:
z

array(['1', '2', '3', 'a'], dtype='<U11')

In [9]:
a = np.array([1, 2, 3, '5'])

In [10]:
a

array(['1', '2', '3', '5'], dtype='<U11')

In [11]:
## Bütün integer lar floata dönüşecek

b = np.array([1, 2, 3, 4.5])

In [12]:
b

array([1. , 2. , 3. , 4.5])

### Not:

* Numpy hızlı nümerik işlemler yapabilmeye yarar.

* np referansı ile numpy e ulaşırız

* numpy array lerinde homojen veri tipi olması gerekir ya hepsi integer, ya hepsi float ya hepsi str olmalı

In [13]:
## bütün integer lar ve float lar stringe dönüşecek

c = np.array([1, 2, 3, 4.5, '2'])

In [14]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

# 2. Lesson: Array lere Manuel Tip Verme

* Array in elemanlarının tipinin ne olacağını özellikle belirtebiliriz.

In [19]:
x = np.array([1, 2, 3, 4.6])

In [20]:
x

array([1. , 2. , 3. , 4.6])

In [21]:
x = np.array([1, 2, 3, 4.6], dtype = 'int32')

In [22]:
x

array([1, 2, 3, 4])

In [23]:
x = np.array([1, 2, 3, 4.6], dtype = 'str')

In [24]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [25]:
x = np.array(['a'], dtype = 'int32')

ValueError: invalid literal for int() with base 10: 'a'

* Hata verdi çünkü string integer a dönüşemez

In [26]:
x = np.array(['5'], dtype = 'int32')

In [27]:
x

array([5])

In [29]:
x = np.array(['4.2'], dtype='int32')

ValueError: invalid literal for int() with base 10: '4.2'

# 3. Lesson: Zero Array

In [1]:
import numpy as np

## Elemanları 0 lardan Oluşan Array Oluşturmak

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Elemanları Olardan Oluşan Multidimensional Array Oluşturmak

In [4]:
# 3 row(satır) ve 4 column(sütun)u olan bir array oluşturmak
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros(3,4)

TypeError: data type not understood

In [7]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros([3,8,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [10]:
np.zeros(2, dtype = int)

array([0, 0])

In [11]:
np.zeros((1,2), dtype = int)

array([[0, 0]])

In [12]:
# ''lerden oluşan string array i oluşturmak
np.zeros((1,2), dtype = str)

array([['', '']], dtype='<U1')

In [13]:
np.zeros((2,3), dtype = bool)

array([[False, False, False],
       [False, False, False]])

# 4.Lesson: Specific Element Array

In [14]:
import numpy as np

## Belirtilen Bir Elemandan Array Oluşturmak

In [15]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [17]:
np.full(4,5,5)
# hata verir çünkü yorumlayamıyor
#ilk girilen shape, 2.içine ne yazacağını , 3. ise datatype
# Yani 4 shape, 5 yazıyor içine, 5 datatype ı ama 5 diye bir datatype yok o yüzden hata veriyor

TypeError: data type not understood

In [18]:
np.full(4,5)
# 4 shape, 5 ile dolduruyor
# 4 elemanlı 

array([5, 5, 5, 5])

In [19]:
np.full((4,5), 'a')
# 4 satır, 5 sütun a dan oluşan

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [21]:
np.full((4,5), 5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [22]:
str(5.2)

'5.2'

In [23]:
np.full((4,5), 5.2, dtype = 'str')

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [25]:
np.full((4,5), '5.2')

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

In [26]:
np.full(2,3)

array([3, 3])

# 5.Lesson: Ardışık Sayılardan Array Oluşturmak

In [27]:
import numpy as np

## Ardışık Sayılardan Array Oluşturmak

In [34]:
# [0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [32]:
np.arange(2,12,-2)

array([], dtype=int32)

In [33]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

# 6.Lesson: Dividing Interval

In [35]:
import numpy as np

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

* Belirlenen [başlangıç, bitiş] değerine göre başlangıç ve bitişi dahil edecek şekilde aralığı eşit uzaklıkta noktalara bölmeyi göreceğiz.

In [36]:
# Default olarak 50 nokta döndürür.
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

## Kaç parçaya Böleceğini Belirtmek

In [37]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [38]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [39]:
np.linspace(1,2,num= 3, endpoint = False)

array([1.        , 1.33333333, 1.66666667])

In [40]:
# 0 ve 1 arasında (0-1 dahil olacak şekilde) 30 nokta üretmek
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [41]:
np.linspace(1.5,4.7, 3)

array([1.5, 3.1, 4.7])

In [42]:
np.linspace(1,30)

array([ 1.        ,  1.59183673,  2.18367347,  2.7755102 ,  3.36734694,
        3.95918367,  4.55102041,  5.14285714,  5.73469388,  6.32653061,
        6.91836735,  7.51020408,  8.10204082,  8.69387755,  9.28571429,
        9.87755102, 10.46938776, 11.06122449, 11.65306122, 12.24489796,
       12.83673469, 13.42857143, 14.02040816, 14.6122449 , 15.20408163,
       15.79591837, 16.3877551 , 16.97959184, 17.57142857, 18.16326531,
       18.75510204, 19.34693878, 19.93877551, 20.53061224, 21.12244898,
       21.71428571, 22.30612245, 22.89795918, 23.48979592, 24.08163265,
       24.67346939, 25.26530612, 25.85714286, 26.44897959, 27.04081633,
       27.63265306, 28.2244898 , 28.81632653, 29.40816327, 30.        ])

# 7.Lesson: Normal Distribution(Dağılım) Array

In [44]:
import numpy as np

## Normal Distribution dan Çekilmiş Değerler İle Array Oluşturmak

* (mean, std, array size)
* (ortalama,standart sapma, nasıl birshape ile oluşturacağını söyler) 

In [48]:
np.random.normal(0,1,(4,5))
# 0rtalaması 0, standart sapmas1, 4satır ve 5 sütundan bir array oluşturuyor

array([[ 0.0400203 ,  0.46367596, -0.25182152,  0.41626772, -0.62737574],
       [-0.90201556, -0.13211469,  0.44204424,  0.71834024,  0.41278459],
       [-0.19988219,  0.60741606, -0.55069868, -2.59807242, -1.94550603],
       [ 0.77762543,  0.05480043, -0.34456081, -1.11649408,  0.66965232]])

In [46]:
np.random.normal(0,100,(4,5))

array([[ 121.71454989,  -67.82758173,  -17.31397753, -122.63572147,
         -89.61499649],
       [ -37.88786669,  -49.44116886,  -92.74413909,  -12.04917815,
        -275.95084358],
       [ -97.07147893,   15.54878014,  245.49543381,   15.77755268,
         -61.41500071],
       [ -52.74530252,   73.00112397, -144.732281  ,   57.4725039 ,
          56.35716656]])

# 8.Lesson: Random Integer Array

In [49]:
import numpy as np

## Random Integer lar İle Array Oluşturmak

* [low, high)

In [50]:
np.random.randint(1,10,(3,4))

array([[9, 1, 6, 7],
       [1, 7, 2, 7],
       [6, 7, 8, 9]])

In [51]:
np.random.randint(1,10,(3,5,5))

array([[[7, 4, 7, 2, 8],
        [5, 8, 1, 1, 9],
        [5, 4, 3, 2, 3],
        [3, 9, 1, 4, 7],
        [9, 7, 4, 8, 3]],

       [[4, 9, 3, 5, 4],
        [3, 1, 6, 8, 6],
        [5, 9, 8, 1, 7],
        [6, 8, 8, 6, 3],
        [1, 3, 2, 2, 9]],

       [[5, 3, 9, 4, 4],
        [6, 8, 4, 8, 5],
        [8, 9, 4, 6, 9],
        [3, 1, 1, 9, 8],
        [3, 4, 5, 8, 9]]])

In [52]:
np.random.randint(1,2)

1

In [53]:
d = {}

for _ in range(20000):
    val = np.random.randint(1,11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [54]:
d

{10: 2010,
 4: 1918,
 3: 1934,
 1: 1975,
 7: 2008,
 8: 2072,
 9: 2113,
 5: 1953,
 2: 2098,
 6: 1919}

# 9.Lesson: Identity Matrix

In [55]:
import numpy as np

## Idendity (birim) Matris Oluşturmak

* [low,high)

In [56]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [57]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# 10.Lesson: Array Operations

In [59]:
import numpy as np

## Array İşlemleri

In [60]:
# * operatörü iki list arasında tanımsızdır, hata verir

a = [1, 2, 3]
b = [2, 4, 8]

a * b

TypeError: can't multiply sequence by non-int of type 'list'

* List ile integer çarpılırsa ard arda concatenataion(birleştirme) yapar

In [61]:
[2, 4, 8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [63]:
[2, 4, 8] + [2, 4, 8] + [2, 4, 8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

*  *(yıldız) operatörü iki numpy array i arasında tanımlıdır, element-wise(eleman bazlı) çarpma yapar

In [64]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x * y

array([ 2,  8, 24])

* element-wise çarpım yaptığı için çarpılan iki array in eleman sayısı aynı olmalı

In [65]:
x2 = np.array([1, 2, 3])
y2 = np.array([2, 4, 8, 10])

x2 * y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [66]:
a = [1, 2, 3]
b = [2, 4, 8]

In [67]:
a + b

# concat yapar

[1, 2, 3, 2, 4, 8]

In [68]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [69]:
x + y

array([ 3,  6, 11])

In [70]:
a

[1, 2, 3]

In [71]:
3 * a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [72]:
x

array([1, 2, 3])

In [73]:
3 * x

array([3, 6, 9])

* değer güncellemek için

In [74]:
x = x* 3

In [75]:
x

array([3, 6, 9])

In [76]:
np.array([3,5,9])*3 

array([ 9, 15, 27])

# 11. Lesson: Array Attribute

In [77]:
import numpy as np

## Array Attribute ları

### Shape

In [81]:
x = np.zeros((2,3))
print(x)

# 2 rows, 3 columns

[[0. 0. 0.]
 [0. 0. 0.]]


In [82]:
y = np.zeros((2, 5, 4))
print(y)

# 2 tane 5x4 lük array , 5 rows, 4 columns 

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [85]:
x.shape

# kodu bize x in kaça kaçlık old verir , diamontionlarını verir

(2, 3)

In [84]:
y.shape

(2, 5, 4)

### ndim

* ndim: kaç diamantion (boyutlu) old verir 

In [86]:
x.ndim

2

In [87]:
y.ndim

3

### size

In [88]:
x.size

6

In [89]:
y.size

40

* size kaç elemanlı olduğunu verir

### dytpe

In [94]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [95]:
x.dtype

dtype('float64')

In [96]:
y = np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [97]:
y.dytpe

AttributeError: 'numpy.ndarray' object has no attribute 'dytpe'

### Not: 
* x.shape, Array'in kaça kaçlık olduğunu(x,y) verir. - - - x.ndim, Array'in kaç boyutlu olduğunu verir. - - - x.size, Array'in boyutunu, kaç elemana sahip olduğunu verir. - - - x.dtype, Array'in elemanlarının veri tipini verir.

# 12.Lesson: Reshape

In [1]:
import numpy as np

## Reshaping

* Reshaping mantığı bize elimizdeki array in içindeki yapıı başka bir şekilde ifade etmemize yarar.

* Önemli olan reshape yapacağımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması , yani size nın aynı olması

In [2]:
a = np.arange(1,11)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Not: bir ustteki array in diamontion u 1 çünkü sadece 10 tane sayı var row ve column yok

In [3]:
a.ndim

1

In [4]:
a.size

10

In [6]:
a.reshape(2,5)# a yı 2,5 formatına dönüştür demek yani 2 row ve 5 column olacak şekilde

# a yı 2,5 formatına dönüştür demek yani 2 row ve 5 column olacak şekilde

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
a.reshape(2,5).ndim

# a nın diamontion unu verir

2

* Eleman sayısı tutmasaydı hata alırdık

In [11]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

## - 1 ile Boyuta Karar Vermek

In [14]:
a.reshape(-1,2)

# a.reshape(5,2) ile aynı anlama gelir. size belli 2 diamonts var biri belli 2 olcak size 10 zaten a.size = 10 olcak yani 2.size = 10 olcak ve size 5 gelir ve dolayısıyla 5,2 olarak alıyor  

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Yeni Boyut Eklemek

In [15]:
a=np.arange(1,11)

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a[np.newaxis, :]

# : bütün hepsini al demek, üstteki ile farkı 1 row 10 column var mantığını aldı


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [20]:
a[np.newaxis :].shape

# 

(10,)

In [22]:
# column vector

a[: , np.newaxis]

# 10 row, 1column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [23]:
a[:, np.newaxis].shape

(10, 1)

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* None newaxis in yaptığının aynısını yapar

In [25]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [26]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [27]:
b=np.arange(1,7)

In [28]:
x=b[np.newaxis,:]

In [29]:
x[:, np.newaxis].shape

(1, 1, 6)

In [30]:
x.size

6

In [31]:
x.shape

(1, 6)

# 13.Lesson: Concatenation

In [32]:
import numpy as np

## Concatenation 

* Birleştirme işlemi yapar

In [34]:
a = np.array([1, 2, 3, 4])

In [35]:
b = np.array([5, 6, 7, 8])

In [36]:
a

array([1, 2, 3, 4])

In [37]:
b

array([5, 6, 7, 8])

In [45]:
# a veya b güncellenmez

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* python listlerini de numpy array leri ile concatenation a sokabiliriz.

In [46]:
l = [10,11]

In [47]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [50]:
l = [10, 11, 11.2]

In [51]:
np.concatenate([a, b, l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [52]:
l = [10, 11, '11.2']

In [53]:
np.concatenate([a, b, l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U11')

* python tuple larını da numpy array leri ile concatenation a sokabiliriz.

In [54]:
l = (10, 11)

In [55]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

## Size Missmatch

In [56]:
a

array([1, 2, 3, 4])

In [63]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [64]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
x.size

6

In [66]:
x.shape

(2, 3)

In [67]:
a.shape

# 4 sayım var ama row column mantığı yok dimontion u 1

# diamontion u 2 olsaydı row column mantığı olurdu

# o yüzden (4,) şeklinde cevap veriyor

(4,)

In [69]:
# shape missmatch

# aşağıdaki  kod hata verir çünkü x te row column mantığı var a da yok

np.concatenate([x, a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [70]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
np.concatenate([x, x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* axis = 0 düşey doğruldu demek

* axis = 1 yatay doğrultuda demektir

* default olarak hiçbişi belirtmezsek düşey kabul eder düşeye ekler

* düşeyler row yataylar column yani axis = 0 dersek altına yazar yani yeni row oluşur

* axis = 1 dersek sağına yazar yani yeni column oluşur

# 14.Lesson: Stack

In [72]:
import numpy as np

# Stack

* Stack mantığını yeni dimension ekleyip üzerinde concatenation yaparak da sağlayabiliriz

### stack

In [73]:
a = np.array([1, 2, 3, 4])

In [74]:
b = np.array([5, 6, 7, 8])

In [75]:
a.shape

(4,)

In [76]:
b.shape

(4,)

* stack mantğı birleştirir ama farklı dimension katar. farklı row larda ya da kolonlarda yerleştirmemizi sağlar.

In [77]:
np.stack([a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
np.stack([a, b], axis =1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# 15.Lesson: Splitting

In [79]:
import numpy as np

## Splitting

In [108]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [109]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [110]:
# [0, 1], [2, 3, 4, 5], [6, 7]

np.split(l, [2, 6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [111]:
np.split(l, [3, 5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

## Split in Sonucunu Birden Çok Değişkene Eşitleme

In [112]:
a, b = (1, 10)

In [113]:
print(a)
print(b)

1
10


In [114]:
x, y, z = np.split(l, [2, 6])

In [115]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


## vsplit

* vertable split

In [116]:
a = np.arange(20).reshape(2, 10)

In [117]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [118]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [119]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## hsplit

In [120]:
a = np.arange(20).reshape(2,10)

In [121]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [122]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [96]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [97]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [98]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [99]:
x, y = np.hsplit(a, [2])

In [101]:
print(x)


[[ 0  1]
 [10 11]]


In [102]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [103]:
x, y, z = np.hsplit(a, [2,4])

In [104]:
print(x)

[[ 0  1]
 [10 11]]


In [105]:
print(y)

[[ 2  3]
 [12 13]]


In [106]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


* vsplit row lara göre böler ama böldüğünde oluşan parçaların column ları eşit olur

* hsplit column lara göre böler ama böldüğünde oluşan parçaların row ları eşit olur

In [127]:
a=np.arange(20).reshape(5,4) 

In [128]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [129]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# 16.Lesson: Sorting

In [130]:
import numpy as np

## Sorting

In [131]:
a = np.array([20, 32, 5, 30, 10])

In [132]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [133]:
# a yı günceller

a.sort()

# inplace(a = np.sort(a) ile aynı)

In [134]:
a

array([ 5, 10, 20, 30, 32])

### argsort

In [135]:
a = np.array([3, 1, 6, 5, 4, 2])

In [136]:
# küçükten büyüğe sıralanmış elemanların indexlerini döndürür

idxs = np.argsort(a)

In [137]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)

# 17.Lesson: Multidimensional Array lerde Indexleme

In [1]:
import numpy as np

## Multidimensional Array lerin Elemanlarına Ulaşmak

In [2]:
a = np.arange(1, 21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[0]

array([1, 2, 3, 4, 5])

In [5]:
a[1]

array([ 6,  7,  8,  9, 10])

In [6]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
a[0,0]

1

In [8]:
a[0][0]

1

In [9]:
a[1,1]

7

In [10]:
a[0, 1]

2

In [17]:
a.ndim

# 2 çünkü row-column mantığından oluşuyor 

2

In [18]:
a[0]

array([1, 2, 3, 4, 5])

In [19]:
a[0].ndim
# 1 çünkü sadece row dan oluşuyor

1

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
a[1,1] = 10

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
# Array in veri tipi neyse ona cast olur, array in veri tipini dönüştürmez

a[1,1] = 20.40

In [24]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
a[1,1] = '11'

In [26]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 11,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
a[1,1] = '30.5'

# iki kademeli dönüşümleri yapamıyor yalnızca tek kademeliler

ValueError: invalid literal for int() with base 10: '30.5'

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 11,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
a[1,1] = 'a'

# yine iki kademeli o yüzden hata veriyor.

ValueError: invalid literal for int() with base 10: 'a'

## Slice Indexing

In [33]:
a = np.arange(1,21).reshape(4,5)

In [34]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
a[1]

array([ 6,  7,  8,  9, 10])

In [36]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
a[:2]

# başta bişi belirtilmezse 0 kabul eder 0:2 ile aynı görevi yapar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
a[0:]

# sağ kısımda bişi belirtilmezse sonuna kadar hepsini alır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
a[1:]

# 1.indexten itibaren hepsini verir

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
a[:]

# baştakini 0 kabul ediyor sondakini de hepsini alıyor

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
a[::2]

# hepsini alıyor ama 2 şer atlıyor

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [47]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
a[2,3]

14

In [51]:
# bütün row ları al ama sadece 3. indexteki column u al
# 3. column un tüm row larla kesişimini alıyor

a[:,3]

array([ 4,  9, 14, 19])

In [56]:
a[::2,3]

# 2 li atlayarak 3.column u al 4 ü yazdı 2 aralık atladı 4 ü aldıili aralık atladı tekrar başa döndü

array([ 4, 14])

In [57]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
a[0]

array([1, 2, 3, 4, 5])

In [59]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
a[2,3]

14

In [61]:
# bütün row ları al ama sadece 3.column u al
a[:,3]

array([ 4,  9, 14, 19])

In [63]:
a[:,3].shape

(4,)

In [64]:
a[::2,3]

array([ 4, 14])

In [66]:
a[0,:]
# 0. rowu al

array([1, 2, 3, 4, 5])

In [67]:
a[0]

array([1, 2, 3, 4, 5])

In [68]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
a[0,2:4]

# 0. row un 2 ile 4 arasını al

array([3, 4])

In [79]:
a[:2,:3]

# en baştan başla 2.rowa kadar ve yine en baştan başla 3.columna kadar al 

array([[1, 2, 3],
       [6, 7, 8]])

In [80]:
a[0:2,0:3]

# üstteki ile aynı

array([[1, 2, 3],
       [6, 7, 8]])

In [81]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
a[::,:4]

# hepsini al ama 4.column a kadar al

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [83]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [84]:
a=np.arange(1,13).reshape(3,4) 

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [87]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
a[1::2]

array([[5, 6, 7, 8]])

# 18.Lesson: Fancy Index

In [89]:
import numpy as np

## Fancy Indexing

* Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları veya belirli sayıda atlaya atlaya elemanları almayı gördük. Fancy indexing ile birkaç tane belirli indexteki elemanı bana döndür diyebilmiş olacağız.

In [90]:
x = np.arange(1, 15)

In [91]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
idxs = [4, 5, 7, 11]

In [93]:
# 4, 5, 7 ve 11. index teki elemanları döndürür.

x[idxs]

array([ 5,  6,  8, 12])

In [97]:
idxs = [4, 5, 7, 1]

In [98]:
x[idxs]

array([5, 6, 8, 2])

In [94]:
a = np.arange(12).reshape(3,4)

In [95]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a[0:2,1]

# virgülden önceki row, sonraki columnda

# en baştan 2.row a kadar al, 1.column ile kesişimini al

array([1, 5])

In [105]:
a[0:2,1].shape

(2,)

In [106]:
a[0:2, 1:3]

# en baştan 2.row a kadar al, 1.column dan 3. column a kadar al

array([[1, 2],
       [5, 6]])

In [101]:
a[0:2, 1:3].shape

(2, 2)

In [102]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a[0, [1,3]]

# 0. index teki rowu al, 1.ve 3.index teki column değerlerini ver

array([1, 3])

In [111]:
a[0:, [1,3]]

# en baştan başla tüm row ları tara, 1.ve 3.columnu olduğu gibi al

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [112]:
a = np.arange(20).reshape(4,5)

In [113]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [114]:
idx1 = [1, 3, 2]

In [115]:
idx2 = [3, 0, 2]

In [117]:
a[idx1, idx2]

# 1,3 elemanı, 3,0 elemanı, 2,2 elemanını index olarak böyle buluyor

array([ 8, 15, 12])

In [119]:
a[idx1][idx2]


IndexError: index 3 is out of bounds for axis 0 with size 3

* Fancy indexing sonucunu belirli değerlere eşitlemek

In [120]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [121]:
x[[1, 2, 3]] = 20

In [122]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
x=np.arange(9)

In [125]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
x[[1, 2, 5]] = [100, 200, 300]

In [128]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

In [131]:
a=np.arange(1,13).reshape(3,4) 

In [132]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
b=a[1,(1,3)]

In [134]:
b

array([6, 8])

In [135]:
b.ndim

1

# 19.Lesson: Subarray

In [136]:
import numpy as np

## Subarray

* Array in bir alt parçasına erişip onunla işlem yapmaktır

In [137]:
a = np.arange(1,21).reshape(4,5)

In [138]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [145]:
b = a[:2, :3]

# baştan başla 2.row akadar al, column da da en baştan başla 3.ye kadar al

In [146]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [147]:
b.ndim

2

In [148]:
b[0,0] = 100

In [149]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [150]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## Copy

* copy() metodunu kullanırsak subarray in değerinin değişmesi orijinal array i etkilemez

In [151]:
a = np.arange(1,21).reshape(4,5)

In [152]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [153]:
b = a[:2,:3].copy()

In [154]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [155]:
b[0,0] = 100

In [156]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [157]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# 20.Lesson: Filter

In [158]:
import numpy as np

## Conditional Indexing

In [159]:
a = np.arange(1, 10)

In [160]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [162]:
a[a<5]

array([1, 2, 3, 4])

In [163]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
filt = a < 3

In [165]:
a[filt]

array([1, 2])

In [166]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
b=np.array([2, 3, 4, 5, 6, 7, 8, 11])

In [175]:
b

array([ 2,  3,  4,  5,  6,  7,  8, 11])

In [176]:
a == b 

<ipython-input-176-239ceb193c1a>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

In [180]:
a[a==b]

<ipython-input-180-3fd39fde0edb>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a[a==b]


array([], shape=(0, 9), dtype=int32)

In [181]:
b[a==b]

<ipython-input-181-d7a40e0d896a>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  b[a==b]


array([], shape=(0, 8), dtype=int32)

In [182]:
# broadcasting

a ==[1]

array([ True, False, False, False, False, False, False, False, False])

In [183]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [184]:
# normalde and or ile kurduğumuz mantığı numpy da kullanamıyoruz

(a<3) or (a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [185]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [186]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [187]:
filt = (a<3) | (a>5)

In [188]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [189]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [190]:
a[(a>3) & (a<=5)]

array([4, 5])

## Filtrenin Değili

In [192]:
a = np.arange(1,21).reshape(4,5)

In [193]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [194]:
filt = a < 5

In [195]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [196]:
a[filt]

array([1, 2, 3, 4])

In [197]:
filt = (a > 5) & (a < 9)

In [200]:
a[!((a>5) & (a<9))]

# not, ! , and, or gibi durumlar numpy da kullanılamıyor

SyntaxError: invalid syntax (<ipython-input-200-ce005448bd06>, line 1)

In [201]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [202]:
# numpy da değili tilda ~ ile yapıyoruz

~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [203]:
filt = ~((a>5) & (a<9))

In [204]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Multidimensional Array lerde Conditional Indexing

In [205]:
a = np.arange(1,21).reshape(4,5)

In [206]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [207]:
type(a)

numpy.ndarray

In [208]:
type(a<7)

numpy.ndarray

In [209]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [210]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [211]:
a[a<7].shape

(6,)

In [212]:
a = np.array([1, 2, 3,None])

In [213]:
a

array([1, 2, 3, None], dtype=object)

In [214]:
a == None

array([False, False, False,  True])

In [215]:
a[a==None]

array([None], dtype=object)

In [226]:
x=np.arange(-5,3).reshape(2,4)

In [227]:
x

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2]])

In [228]:
x[(x<0) & (x==2)]

array([], dtype=int32)

In [229]:
x[(x<0) | (x==2)]

array([-5, -4, -3, -2, -1,  2])

# 21.Lesson: Sum

In [230]:
import numpy as np

## Sum

* Verilen Condition ı kaç elemanın sağladığını buldum.

* Sum metodu belli axis ler üzerindeki değerleri ya da tüm değerleri toplamamıza yarar

In [231]:
a = np.arange(1,21).reshape(4,5)

In [232]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [233]:
np.sum(a)

210

In [234]:
filt = a < 5

In [235]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [236]:
np.sum(filt)

4

In [237]:
a[filt]

array([1, 2, 3, 4])

In [238]:
np.sum(a[filt])

10

In [239]:
filt = (a>5) &(a<9)

In [240]:
np.sum(filt)

3

In [241]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [242]:
a[filt]

array([6, 7, 8])

In [244]:
np.sum(a[(a>5) & (a<9)])

21

In [245]:
filt = ~ ((a>5) & (a<9))

In [246]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [247]:
np.sum(~((a>5) & (a<9)))

17

In [248]:
np.sum(a[~((a>5) & (a<9))])

189

## Belirli Axis Üzerinde Toplama

In [249]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [250]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [251]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

In [252]:
np.sum(a)

210

In [253]:
a=np.arange(1,21).reshape(4,5)

In [254]:
 np.sum(a,axis=0) 

array([34, 38, 42, 46, 50])

In [255]:
b =  np.sum(a,axis=0) 

In [256]:
b

array([34, 38, 42, 46, 50])

In [257]:
b.shape

(5,)

# 22. Lesson: All

In [258]:
import numpy as np

## All

* Tüm elemanlar verilen şartı sağlıyor mu diye kontrol etmek

In [259]:
a = np.arange(1,21).reshape(4,5)

In [260]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [261]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [262]:
np.all(a>-1)

True

In [267]:
np.all(a>5)

False

In [263]:
filt = a > -1

In [264]:
np.all(filt)

True

In [268]:
np.all(a>5, axis =1)

array([False,  True,  True,  True])

In [269]:
np.all(a>5, axis = 0)

array([False, False, False, False, False])

In [271]:
a=np.arange(1,21).reshape(4,5)

In [273]:
np.all(a>8,axis=1)

array([False, False,  True,  True])

In [272]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# 23.Lesson: Any

In [270]:
import numpy as np

## any()

* Herhangi bir eleman verilen şartı sağlıyor mu diye kontrol etmek

In [274]:
a = np.arange(1,21).reshape(4,5)

In [275]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [276]:
a > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [277]:
np.any(a>17)

True

In [278]:
np.any(a>17, axis = 0)

array([False, False,  True,  True,  True])

In [279]:
np.any(a >17, axis = 1)

array([False, False, False,  True])

In [280]:
np.any(a>4,axis=0) 

array([ True,  True,  True,  True,  True])